### ISSUE TITLE
OCI image not containing /bin/sh

### ISSUE THREAD

**Issue by cclerget** [sylabs/cri#140]
Some OCI images doesn't contain `/bin/sh`, so we can't use `/.singularity.d/actions/runscript` ending with error `exec /.singularity.d/actions/run failed: no such file or directory`, in this case we need to grab image data directly and store entrypoint/cmd for direct execution.

**Comment by sashayakovtseva** [comment]
As decided with @cclerget and the rest, we will pull statically linked sh from [busybox](https://busybox.net/downloads/binaries/1.21.1/) and bind mount it in this case
